### ISSUE TITLE
[Question] Will it be able to use models from hugging face?

### ISSUE THREAD

**Issue by cigoic** [xakpc/DotnetPrompt#3]
Browsing the internet, I found some tutorial chaining LangChain, OpenAI...etc. But all working under python environment.

Would DotnetPrompt be able to do similar tasks by itself? Thanks.

**Comment by xakpc** [comment]
Hey @cigoic 

Currently, Hugging Face is not supported. However, it is possible to implement it easily as the models in DotnetPrompt function as REST clients. I have yet to explore Hugging Face's capabilities.
